site_name: Solid Enigma
theme:
  name: material
  features:
    - content.code.annotate
  icon:
    logo: material/cable-data

  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: default
    primary: cyan
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  - media: "(prefers-color-scheme: light)"
    scheme: slate
    primary: cyan
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
